[object]
name = "av.pix.edgedetect"
digest = "Detect edges in an image"
description = "Perform edge detection on an image and output as black-white image."

[messages]
[messages.jit_gl_texture]
digest = "Process an incoming texture"
description = "Process an incoming texture"

[messages.float]
digest = "Function depends on inlet"
description = """
Function depends on inlet<br/><br/>
inlet 0: enable/disable processing <br/>
inlet 1: detection threshold (default = 0.5) <br/>
inlet 2: linewidth in pixels (default = 3) <br/>
inlet 3: invert the output (default = 0)
"""
args = [ { name = "float", type = "float", optional = 1 } ]

[messages.int]
digest = "Function depends on inlet"
description = """
Function depends on inlet<br/><br/>
inlet 0: enable/disable processing <br/>
inlet 1: detection threshold (default = 0.5) <br/>
inlet 2: linewidth in pixels (default = 3) <br/>
inlet 3: invert the output (default = 0)
"""
args = [ { name = "int", type = "int", optional = 1 } ]

# [messages.list]

[arguments]
[arguments.threshold]
digest = "detection threshold (default = 0.5)"
type = "float"
optional = 1

[arguments.linewidth]
digest = "linewidth in pixels (default = 3)"
type = "float"
optional = 1

[arguments.invert]
digest = "invert the output (default = 0)"
type = "bool"
optional = 1

[attributes]
[attributes.bypass]
digest = "bypass the pixel processing"
type = "bool"
size = 1
default = { value = 0, size = 1, type = 'bool' }
