[object]
name = "av.pix.gamma.correct"
digest = "convert from sRGB to linear color space"
description = """Convert from sRGB (standard Red Green Blue) to linear color space. Also called gamma-expansion.<br/><br/>

Useful for when processing the colors of a movie. First convert the movie to linear colorspace with expand. Then process the colors. Then convert back to sRGB colorspace with correct. Also useful when converting a full 3D generated scene to sRGB colorspace (only gamma-correction).<br/><br/>

Note: Max9 users can also use jit.fx.srgb2lin and jit.fx.lin2srgb"""

[messages]
[messages.jit_gl_texture]
digest = "Texture to convert from sRGB to linear color space"
description = "Texture to convert from sRGB to linear color space"
args = [ { name = "jit_gl_texture", type = "jit_gl_texture", optional = 0 } ]

# [arguments]

# [attributes]