[object]
name = "av.pix.displace"
digest = "Displace a texture with another texture"
description = "Displace a texture based on the color values from another texture"

[messages]
[messages.jit_gl_texture]
digest = "Function depends on inlet"
ddescription = """
inlet 0: Texture 1 to blend<br/>
inlet 1: Texture 2 to blend<br/>
"""
args = [ { name = "jit_gl_texture", type = "jit_gl_texture", optional = 0 } ]

[messages.int]
digest = "Function depends on inlet"
description = """
Function depends on inlet<br/><br/>
inlet 0: enable/disable processing <br/>
inlet 1: none <br/>
inlet 2: displacement amount (default = 0.1) <br/>
"""
args = [ { name = "int", type = "int", optional = 1 } ]

[messages.float]
digest = "Function depends on inlet"
description = """
Function depends on inlet<br/><br/>
inlet 0: enable/disable processing <br/>
inlet 1: none <br/>
inlet 2: displacement amount (default = 0.1) <br/>
"""
args = [ { name = "float", type = "float", optional = 1 } ]

[arguments]
[arguments.amount]
optional = 1
type = "float"
digest = "displacement amount (default = 0.1)"

[attributes]
[attributes.bypass]
digest = "bypass the pixel processing"
description = "bypass the pixel processing"
type = "bool"
size = 1
default = { value = 0, size = 1, type = 'bool' }
