[object]
name = "av.pix.glitch"
digest = "Glitch a texture by displacing it with noise"
description = """Glitch a texture by displacing it with noise. Choose your own noise dimensions for different glitch resolutions. Send a bang to trigger a new noise.<br/><br/>

mode 0: no color displacement, only position <br/>
mode 1: red/cyan displacement <br/>
mode 2: yellow/blue displacement <br/>
mode 3: magenta/green displacement
"""

[messages]
[messages.jit_gl_texture]
digest = "Process an incoming texture"
description = "Process an incoming texture"
args = [ { name = "jit_gl_texture", type = "jit_gl_texture", optional = 0 } ]

[messages.int]
digest = "Function depends on inlet"
description = """
Function depends on inlet<br/><br/>
inlet 0: enable/disable processing <br/>
inlet 1: glitch amount (default = 0.05) <br/>
inlet 2: <br/>
"""
args = [ { name = "int", type = "int", optional = 1 } ]

[messages.float]
digest = "Function depends on inlet"
description = """
Function depends on inlet<br/><br/>
inlet 0: enable/disable processing <br/>
inlet 1: glitch amount (default = 0.05) <br/>
inlet 2: <br/>
"""
args = [ { name = "float", type = "float", optional = 1 } ]

[messages.bang]
digest = "Function depends on inlet"
description = """
Function depends on inlet<br/><br/>
inlet 0: <br/>
inlet 1: <br/>
inlet 2: generate new noise texture<br/>
"""

[arguments]
[arguments.amount]
optional = 1
type = "float"
digest = "displacement amount (default = 0.1)"

[attributes]
[attributes.mode]
digest = "displacement mode (options: 0: position, 1: red/cyan, 2: yellow/blue, 3: magenta/green, default = 3)"
type = "int"
size = 1

[attributes.dim]
digest = "set the noise dimensions in pixels (default = 3 160)"
type = "list"
size = 2

[attributes.bypass]
digest = "bypass the pixel processing (default = 0)"
type = "bool"
size = 1
default = { value = 0, size = 1, type = 'bool' }

[attributes.filter]
digest = "filter for the texture resampling (options: linear, none)"
type = "symbol"
size = 1
default = { value = "linear", size = 1, type = 'symbol' }
